version: '2.1'

  # REPEATER SERVICE
  openhop-repeater:
    build: 
      context: .
      args:
        TARGET_HASH: "origin/dev"
        #TARGET_HASH: "dcaa4ac"
    # Added environment variables to try to enable plugin manager
    environment:
      #- OPENHOP_PLUGIN_MANAGER=1        # Possibly NOT needed
      - OPENHOP_PLUGIN_DIR=/var/lib/openhop_repeater/plugins
      - OPENHOP_ENABLE_PLUGINS=true
    privileged: true
    cap_add:
      - SYS_RAWIO
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
      - "/dev/spidev0.0:/dev/spidev0.0"
      - "/dev/gpiochip0:/dev/gpiochip0"
    ports:
      - "8000:8000"
      - "8080:8080"
      - "2222:22" #allow inbound ssh
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-api: '1'
      # Balena uses this label to enable GPIO access
      io.balena.features.gpio: '1'
    volumes:
      - config:/etc/openhop_repeater
      - data:/var/lib/openhop_repeater
      # New volume locations for the plugin manager ecosystem
      - openhop_plugins:/var/lib/openhop_repeater/plugins
      - openhop_plugin_cache:/var/cache/openhop_repeater/plugin-manager
    group_add:
      - "plugdev"
      - "gpio"
    restart: always

volumes:
  config:
  data:
  # Add volumes for plugins
  openhop-plugins: # Persistent volume for the plugin manager
  openhop_plugin_cache: # Plugin cache volume
